# pandas series

In [1]:
import pandas as pd
a=[1,2,3,4,5]
se=pd.Series(a)
se

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
type(se)

pandas.Series

# change index name

In [3]:
import pandas as pd
a=[1,2,3,4,5]
se=pd.Series(a ,index=['a','b','c','d','e'])
se

a    1
b    2
c    3
d    4
e    5
dtype: int64

# DataFrame

In [4]:
# using list
import pandas as pd
data=[1,2,3,4,5]
df=pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4
4  5

In [5]:
#using dict
fruits={'fruit':['apple','banana','orange'],'quantity':[10,20,30]}
df=pd.DataFrame(fruits)
df

    fruit  quantity
0   apple        10
1  banana        20
2  orange        30

# creating DataFrame using numpy array

In [6]:
import numpy as np
nparry=np.array([[5000,6000],['Raj','Ravi']])
df=pd.DataFrame({'name':nparry[1],'salary':nparry[0]})
df

   name salary
0   Raj   5000
1  Ravi   6000

# merze operation

In [7]:
# merze operation
player=['player1','player2','player3']
points=[8,9,6]
title=['game1','game2','game3']
df1=pd.DataFrame({'player':player,'points':points})
print(df1)
df2=pd.DataFrame({'player':player,'title':title})
print(df2)
df3=pd.merge(df1,df2,on='player')
df3

    player  points
0  player1       8
1  player2       9
2  player3       6
    player  title
0  player1  game1
1  player2  game2
2  player3  game3

    player  points  title
0  player1       8  game1
1  player2       9  game2
2  player3       6  game3

In [8]:
# merze operation
player=['player1','player2','player3']
points=[8,9,6]
title=['game1','game2','game3']
df1=pd.DataFrame({'player':player,'points':points,'title':title})
df1

    player  points  title
0  player1       8  game1
1  player2       9  game2
2  player3       6  game3

In [9]:
player=['player1','player5','player6']
power=['punch','kick','block']
title=['game1','game5','game6']
df2=pd.DataFrame({'player':player,'power':power,'title':title})
df2

    player  power  title
0  player1  punch  game1
1  player5   kick  game5
2  player6  block  game6

# innermerze

In [10]:
df3=pd.merge(df1,df2,on='player',how='inner')
df3

    player  points title_x  power title_y
0  player1       8   game1  punch   game1

In [11]:
df4=pd.merge(df1,df2,on='title',how='inner')
df4

  player_x  points  title player_y  power
0  player1       8  game1  player1  punch

left merze

In [12]:
df5=pd.merge(df1,df2,on='player',how='left')
df5

    player  points title_x  power title_y
0  player1       8   game1  punch   game1
1  player2       9   game2    NaN     NaN
2  player3       6   game3    NaN     NaN

Right merze

In [13]:
df6=pd.merge(df1,df2,on='player',how='right')
df6

    player  points title_x  power title_y
0  player1     8.0   game1  punch   game1
1  player5     NaN     NaN   kick   game5
2  player6     NaN     NaN  block   game6

In [14]:
df7=pd.merge(df1,df2,on='player',how='outer')
df7

    player  points title_x  power title_y
0  player1     8.0   game1  punch   game1
1  player2     9.0   game2    NaN     NaN
2  player3     6.0   game3    NaN     NaN
3  player5     NaN     NaN   kick   game5
4  player6     NaN     NaN  block   game6

# Join oparation

In [15]:
player=['player1','player5','player6']
power=['punch','kick','block']
title=['game1','game5','game6']
df10=pd.DataFrame({'player':player,'power':power,'title':title},index=['l1','l2','l3'])
df10

     player  power  title
l1  player1  punch  game1
l2  player5   kick  game5
l3  player6  block  game6

In [16]:
player=['player1','player5','player6']
power=['punch','kick','block']
title=['game1','game5','game6']
df12=pd.DataFrame({'player':player,'power':power,'title':title},index=['l2','l3','l4'])
df12

     player  power  title
l2  player1  punch  game1
l3  player5   kick  game5
l4  player6  block  game6

inner join

In [17]:
# inner join with suffixes to avoid overlapping column names
# original error occurred because both DataFrames shared identical column names

result = df10.join(df12, how='inner', lsuffix='_10', rsuffix='_12')
result

   player_10 power_10 title_10 player_12 power_12 title_12
l2   player5     kick    game5   player1    punch    game1
l3   player6    block    game6   player5     kick    game5

In [18]:
df3=df10.join(df12, how='left', lsuffix='_10', rsuffix='_12')
df3

   player_10 power_10 title_10 player_12 power_12 title_12
l1   player1    punch    game1       NaN      NaN      NaN
l2   player5     kick    game5   player1    punch    game1
l3   player6    block    game6   player5     kick    game5

In [19]:
df3=df10.join(df12, how='right', lsuffix='_10', rsuffix='_12')
df3

   player_10 power_10 title_10 player_12 power_12 title_12
l2   player5     kick    game5   player1    punch    game1
l3   player6    block    game6   player5     kick    game5
l4       NaN      NaN      NaN   player6    block    game6

# importing Dataset

In [20]:
data=pd.read_csv('mtcars.csv')
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [21]:
type(data)

pandas.DataFrame

In [22]:
data.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [23]:
data.head(10)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4

In [24]:
data.tail()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.9,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.5,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.5,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.6,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.6,1,1,4,2

In [25]:
data.shape

(32, 12)

In [26]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   model   32 non-null     str
 1   mpg     32 non-null     float64
 2   cyl     32 non-null     int64
 3   disp    32 non-null     float64
 4   hp      32 non-null     int64
 5   drat    32 non-null     float64
 6   wt      32 non-null     float64
 7   qsec    32 non-null     float64
 8   vs      32 non-null     int64
 9   am      32 non-null     int64
 10  gear    32 non-null     int64
 11  carb    32 non-null     int64
dtypes: float64(5), int64(6), str(1)
memory usage: 3.1 KB

In [27]:
print(data['mpg'].mean())

20.090625000000003

In [28]:
print(data['mpg'].median())

19.2

In [29]:
print(data['mpg'].std())

6.026948052089104

In [30]:
print(data['mpg'].max())

33.9

In [31]:
print(data['mpg'].min())

10.4

In [32]:
print(data['mpg'].count())

32

In [33]:
data.count()

model    32
mpg      32
cyl      32
disp     32
hp       32
drat     32
wt       32
qsec     32
vs       32
am       32
gear     32
carb     32
dtype: int64

In [34]:
data.describe()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

# Data Cleaning

In [35]:
data=data.rename(columns={'Unnamed: 1':'model'})
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# manupalating Data set

In [36]:
data.iloc[:,4]

0     110
1     110
2      93
3     110
4     175
5     105
6     245
7      62
8      95
9     123
10    123
11    180
12    180
13    180
14    205
15    215
16    230
17     66
18     52
19     65
20     97
21    150
22    150
23    245
24    175
25     66
26     91
27    113
28    264
29    175
30    335
31    109
Name: hp, dtype: int64

In [37]:
data.iloc[:5,4]

0    110
1    110
2     93
3    110
4    175
Name: hp, dtype: int64

In [38]:
data.mpg

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

In [39]:
#set value
data['am']=1
data

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,1,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,1,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,1,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,1,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,1,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,1,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,1,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,1,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,1,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,1,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,1,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,1,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,1,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,1,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,1,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,1,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,1,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,1,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,1,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

# Sorting Data

In [40]:
data.sort_values(by='mpg',ascending=False)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,1,4,2
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,1,4,2
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,1,3,1
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,1,3,1
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,1,4,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,1,3,2
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,1,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,1,3,1
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,1,4,4
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,1,3,3
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,1,3,3
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,1,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,1,3,2
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,1,3,3
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,1,3,4
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,1,3,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,1,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,1,3,4
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,1,3,4

In [41]:
data.sort_values(by='mpg',ascending=True)

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,1,3,4
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,1,3,4
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,1,3,4
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,1,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,1,3,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,1,3,2
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,1,3,3
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,1,3,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,1,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,1,3,3
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,1,4,4
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,1,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,1,3,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,1,4,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,1,3,2
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,1,3,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,1,3,1
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,1,4,2
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,1,4,2
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1

In [42]:
data['cyl']>6

0     False
1     False
2     False
3     False
4      True
5     False
6      True
7     False
8     False
9     False
10    False
11     True
12     True
13     True
14     True
15     True
16     True
17    False
18    False
19    False
20    False
21     True
22     True
23     True
24     True
25    False
26    False
27    False
28     True
29    False
30     True
31    False
Name: cyl, dtype: bool

In [43]:
ft1=data['cyl']>6
ft2=data[ft1]
ft2

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,1,3,2
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,1,3,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,1,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,1,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,1,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,1,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,1,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,1,3,4
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,1,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,1,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,1,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,1,3,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8

# Slicing

In [46]:
data[['model','cyl']]

                  model  cyl
0             Mazda RX4    6
1         Mazda RX4 Wag    6
2            Datsun 710    4
3        Hornet 4 Drive    6
4     Hornet Sportabout    8
5               Valiant    6
6            Duster 360    8
7             Merc 240D    4
8              Merc 230    4
9              Merc 280    6
10            Merc 280C    6
11           Merc 450SE    8
12           Merc 450SL    8
13          Merc 450SLC    8
14   Cadillac Fleetwood    8
15  Lincoln Continental    8
16    Chrysler Imperial    8
17             Fiat 128    4
18          Honda Civic    4
19       Toyota Corolla    4
20        Toyota Corona    4
21     Dodge Challenger    8
22          AMC Javelin    8
23           Camaro Z28    8
24     Pontiac Firebird    8
25            Fiat X1-9    4
26        Porsche 914-2    4
27         Lotus Europa    4
28       Ford Pantera L    8
29         Ferrari Dino    6
30        Maserati Bora    8
31           Volvo 142E    4

In [47]:
data[0:3]

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1

In [53]:
data.loc[[1]]

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
1,Mazda RX4 Wag,21.0,6,160.0,110,3.9,2.875,17.02,0,1,4,4